kind: pipeline
type: docker
name: default
steps:

  - name: test
    image: hayd/ubuntu-deno
    commands:
      - make test

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password      
      tags: 
        - "latest"
        - "${DRONE_TAG=${DRONE_COMMIT}}"
