kind: pipeline
type: docker
name: default

environment:
  HELLO: "world"

steps:
  - name: "echo"
    image: alpine
    commands:
      - echo ${HELLO}
      - echo $${HELLO}
      - echo $HELLO
      - echo $$HELLO
      - env