kind: pipeline
type: docker
name: default
steps:

  - name: test
    image: hayd/deno:alpine-1.0.0-rc2
    privileged: true
    commands:
      - apk --no-cache add make git
      - env
      - ls -la /root
      - make test

  - name: cms-image
    image: plugins/docker
    settings:
      config_repo:
        remote: master
        branch: master
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password      
      tags: 
        - "latest"
        - "${DRONE_TAG=${DRONE_COMMIT}}"
