kind: pipeline
type: docker
name: default
steps:

  - name: test
    image: hayd/alpine-deno:1.2.0
    commands:
      - apk --no-cache add make
      - make test

  - name: push
    image: plugins/docker
    settings:
      repo: andrewmclagan/drone-gke
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password      
      tags: 
        - latest
        - ${DRONE_TAG=${DRONE_COMMIT}}
