kind: pipeline
type: docker
name: default
steps:

  - name: dependancies
    image: node:alpine
    commands:
      - yarn install

  - name: test
    image: node:alpine
    commands:
      - yarn run test

  - name: cms-image
    image: plugins/docker
    settings:
      config_repo:
        remote: master
        branch: master
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password      
      tags: 
        - "latest"
        - "${DRONE_TAG=${DRONE_COMMIT}}"
