kind: pipeline
type: docker
name: default

environment:
  HELLO: "world"
  FOO: "bar"

steps:
  - name: "echo"
    image: alpine
    commands:
      - echo ${HELLO}
      - echo $${HELLO}
      - echo $HELLO
      - echo $$HELLO
      - echo ${FOO}
      - echo $${FOO}
      - echo $FOO
      - echo $$FOO
      - env
