apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      foo: <%= FOO %>
      bar: <%= BAR %>
  replicas: 1
  template:
    metadata:
      labels:
        foo: <%= FOO %>
        bar: <%= BAR %>
    spec:
      containers:

        - name: web
          imagePullPolicy: Always
          image: "hello-world:<%= VERSION %>"
          ports:
            - containerPort: 80           
