apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      name: <%= name %>
      version: <%= version %>
      tier: <%= meta.tier %>
      deployment: <%= meta.deployment %>
  replicas: 1
  template:
    metadata:
      labels:
        name: <%= name %>
        version: <%= version %>
        tier: <%= meta.tier %>
        deployment: <%= meta.deployment %>
    spec:
      containers:

        - name: web
          imagePullPolicy: Always
          image: "hello-world:<%= version %>"
          ports:
            - containerPort: 80           
