apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    foo: <%= FOO %>
    bar: <%= BAR %>
    version: <%= VERSION %>
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    foo: <%= FOO %>
    bar: <%= BAR %>
    version: <%= VERSION %>
