apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    name: <%= name %>
    version: <%= version %>
    tier: <%= meta.tier %>
    deployment: <%= meta.deployment %>
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: <%= name %>
    version: <%= version %>
    tier: <%= meta.tier %>
    deployment: <%= meta.deployment %>
